name: 'Auto Assign TimTamTeam'
description: 'Send review requests to TimTamTeam'
author: 'Zara Kay'
branding:
  icon: 'check'
  color: 'blue'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  include-draft:
    description: 'If set to true, DRAFT PRs will also be covered (default=false)'
    required: false
  skip-with-manual-reviewers:
    description: 'If the given nubmer of reviewers is already assigned, auto assign will be skipped'
    required: false

runs:
  using: 'node12'
  main: 'lib/index.js'
